package com.github.archerlml.gymbuddy.model;

import com.github.archerlml.gymbuddy.util.Util;

import java.util.UUID;

/**
 * Created by archerlml on 11/1/17.
 */

public class Entity {

    // generated by server
    public String _id;

    // generated by local
    public String _key;

    public Entity() {
        _key = UUID.randomUUID().toString();
    }

    @Override
    public String toString() {
        return Util.objToJson(this);
    }
}
